-- SmartSociety backend schema for Supabase/PostgreSQL
-- Run this in Supabase SQL Editor on a fresh project/database.

create type user_role as enum ('admin', 'resident', 'security');
create type user_status as enum ('pending', 'approved');
create type flat_status as enum ('occupied', 'vacant', 'under_maintenance');
create type flat_type as enum ('1BHK', '2BHK', '3BHK', 'duplex');
create type resident_role as enum ('owner', 'tenant', 'family_member');
create type complaint_status as enum ('open', 'in_progress', 'resolved', 'closed');
create type payment_status as enum ('pending', 'paid', 'overdue');
create type delivery_status as enum ('received', 'handed_over', 'returned');

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table users (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  email_verified boolean not null default false,
  phone varchar(20) unique,
  hashed_password varchar(255) not null,
  role user_role not null,
  status user_status,
  is_active boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint ck_users_status_resident_only check (
    (role = 'resident' and status is not null)
    or (role <> 'resident' and status is null)
  )
);

create table flats (
  id integer generated by default as identity primary key,
  block varchar(50) not null,
  floor_number integer not null,
  flat_number integer not null,
  status flat_status not null default 'vacant',
  type flat_type not null,
  maintenance_due numeric(10, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint uq_flats_block_flat_number unique (block, flat_number),
  constraint ck_flats_floor_non_negative check (floor_number >= 0),
  constraint ck_flats_maintenance_non_negative check (maintenance_due >= 0)
);

create table residents (
  id integer generated by default as identity primary key,
  user_id integer not null unique references users(id) on delete cascade,
  name varchar(255) not null,
  phone varchar(20) not null,
  email varchar(255) not null,
  flat_id integer references flats(id) on delete restrict,
  role resident_role not null,
  move_in_date date not null default current_date,
  move_out_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint ck_residents_move_out_after_move_in check (
    move_out_date is null
    or move_in_date is null
    or move_out_date > move_in_date
  )
);

create table complaints (
  id integer generated by default as identity primary key,
  resident_id integer not null references residents(id),
  title varchar(255) not null,
  description text not null,
  category varchar(100),
  priority varchar(50),
  summary text,
  image_path varchar(2048),
  status complaint_status not null default 'open',
  rating integer,
  rating_feedback text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table payments (
  id integer generated by default as identity primary key,
  resident_id integer not null references residents(id),
  amount numeric(10, 2) not null,
  currency varchar(10) not null default 'INR',
  status payment_status not null default 'pending',
  due_date timestamptz,
  paid_at timestamptz,
  method varchar(50),
  provider varchar(50),
  provider_order_id varchar(100),
  provider_payment_id varchar(100),
  provider_signature varchar(255),
  idempotency_key varchar(120),
  receipt varchar(120),
  reminder_stage integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table notices (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  content text not null,
  expires_at timestamptz,
  created_by_user_id integer references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table visitors (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  phone varchar(20),
  purpose varchar(255),
  flat_id integer references flats(id) on delete restrict,
  entry_time timestamptz,
  exit_time timestamptz,
  qr_token varchar(120),
  status varchar(50) default 'pending',
  pre_registered_at timestamptz default now(),
  valid_until timestamptz,
  created_by_user_id integer references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table deliveries (
  id integer generated by default as identity primary key,
  vendor varchar(255) not null,
  delivery_person_name varchar(255) not null,
  block_tower varchar(100),
  mobile_number varchar(20),
  delivery_type varchar(50),
  description varchar(255),
  flat_id integer references flats(id) on delete restrict,
  status delivery_status not null default 'received',
  received_time timestamptz default now(),
  handed_over_time timestamptz,
  resident_confirmed_at timestamptz,
  entry_allowed_at timestamptz,
  created_by_user_id integer references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table settings (
  id integer generated by default as identity primary key,
  society_name varchar(255) not null,
  society_address varchar(255) not null,
  society_phone varchar(50) not null,
  society_email varchar(255) not null,
  admin_name varchar(255) not null,
  admin_email varchar(255) not null,
  admin_phone varchar(50) not null,
  notify_visitors boolean not null default true,
  notify_complaints boolean not null default true,
  notify_notices boolean not null default true,
  policy_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table meeting_summaries (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  transcript text not null,
  summary text not null,
  action_items text,
  created_by_user_id integer references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table admin_audit_logs (
  id integer generated by default as identity primary key,
  actor_user_id integer references users(id) on delete set null,
  action varchar(100) not null,
  target_type varchar(100) not null,
  target_id integer,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index ix_users_email on users(email);
create index ix_users_phone on users(phone);
create index ix_residents_user_id on residents(user_id);
create index ix_residents_flat_id on residents(flat_id);
create index ix_complaints_resident_id on complaints(resident_id);
create index ix_payments_resident_id on payments(resident_id);
create index ix_visitors_flat_id on visitors(flat_id);
create index ix_deliveries_flat_id on deliveries(flat_id);
create index ix_admin_audit_logs_actor_user_id on admin_audit_logs(actor_user_id);
create index ix_admin_audit_logs_target_type_target_id on admin_audit_logs(target_type, target_id);

create trigger trg_users_updated_at before update on users
for each row execute function set_updated_at();
create trigger trg_flats_updated_at before update on flats
for each row execute function set_updated_at();
create trigger trg_residents_updated_at before update on residents
for each row execute function set_updated_at();
create trigger trg_complaints_updated_at before update on complaints
for each row execute function set_updated_at();
create trigger trg_payments_updated_at before update on payments
for each row execute function set_updated_at();
create trigger trg_notices_updated_at before update on notices
for each row execute function set_updated_at();
create trigger trg_visitors_updated_at before update on visitors
for each row execute function set_updated_at();
create trigger trg_deliveries_updated_at before update on deliveries
for each row execute function set_updated_at();
create trigger trg_settings_updated_at before update on settings
for each row execute function set_updated_at();
create trigger trg_meeting_summaries_updated_at before update on meeting_summaries
for each row execute function set_updated_at();
create trigger trg_admin_audit_logs_updated_at before update on admin_audit_logs
for each row execute function set_updated_at();

-- Complaint image storage
-- Run this block too if you want complaint photos stored in Supabase Storage.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'complaint-images',
  'complaint-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read complaint images" on storage.objects;
create policy "Public read complaint images"
on storage.objects for select
using (bucket_id = 'complaint-images');

alter table complaints
alter column image_path type varchar(2048);
